### ISSUE TITLE
Вылет, краш, докс, сват

### ISSUE THREAD

**Issue by sqlerrorthing** [SonicallGameXGit/CalculatorMod#1]
Не работает, не складывает 1487+1, вылетает сразу.

**Comment by SonicallGameXGit** [comment]
Сам вчера заметил, попытавшись поиграть с модом.
Исправил недавно, просто при подключении EXP4J я не смог добавить его в код .jar, из-за чего он вызывал не существующие функции. Теперь все работает :)

**Comment by sqlerrorthing** [comment]
все равно вылетает, еще появился этот файл на моем пк.. что это?!

https://github.com/SonicallGameXGit/CalculatorMod/assets/148702857/16fdca7e-ec2b-4f6b-b660-ad3f46ed6fdc

**Comment by sqlerrorthing** [comment]
гей.
